name: ref_mate
description: "RefMate ist eine mobile App, die speziell für Basketball-Schiedsrichter:innen entwickelt wird, um den Alltag rund um das Pfeifen moderner, effizienter und stressfreier zu gestalten. Von Regeltraining über Ansetzungen bis hin zur Honorarübersicht – RefMate ist dein persönlicher Begleiter auf und neben dem Spielfeld."
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
